// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://envzsfdidcnsqxddxpro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudnpzZmRpZGNuc3F4ZGR4cHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDgzMjYsImV4cCI6MjA1OTY4NDMyNn0.8oL5quXETaHFYpwQplHjAzmnN97ID9wWz-pdCNbK2-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);